name: link_learner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl_phone_field: ^3.2.0
  otp_text_field_v2: ^1.0.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.2.0
  timeago: ^3.7.1
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.2
  firebase_messaging: ^15.2.6
  dio: ^5.9.0
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.2.1
  app_links: ^6.4.0
  fluttertoast: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/app_icon_without_name.png"
#   adaptive_icon_background: "#FFFFFF"  
#   adaptive_icon_foreground: "assets/images/app_icon_without_name.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
